version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "xpack.license.self_generated.type=basic"
      # elastic
      - ELASTIC_PASSWORD=123456  # 请替换为你设置的 elastic 密码
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/init:/usr/share/elasticsearch/init  # 挂载初始化脚本
    #      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    entrypoint: [ "/bin/bash", "-c", "/usr/local/bin/docker-entrypoint.sh && /usr/share/elasticsearch/init/init-users.sh" ]
    healthcheck:
      test: curl --fail http://localhost:9200/_cluster/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.2
    container_name: kibana
    environment:
      - "TZ=Asia/Shanghai"
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=123456  # 与初始化脚本中相同的密码
      - I18N_LOCALE=zh-CN
    #    volumes:
    #      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

volumes:
  es_data:
    driver: local

networks:
  elastic:
    driver: bridge
